val passiveAssetRelatedRows = Seq("cash_and_cash_equivalents",
  "shortterm_marketable_securities",
  "shortterm_debt_investment",
  "notes_receivable",
  "dividend_receivable",
  "interest_receivable",
  "other_receivables",
  "current_portion_of_longterm_debt_investment",
  "other_current_assets",
  "noncurrent_assets", // The col could be added
  "available_for_sale",
  "held_to_maturity",
  "longterm_equity_investment",
  "longterm_debt_investment",
  "other_equity_instrument_investment",
  "long_term_receivable",
  "other_noncurrent_assets")
